# SPDX-License-Identifier: MIT
# Validated format, not a claim that every other format is impossible.
monitor.alsa.rules = [
  {
    matches = [ { node.name = "alsa_input.platform-sound.HiFi__Mic__source" } ]
    actions = {
      update-props = {
        audio.format = "S16LE"
        audio.rate = 48000
        audio.allowed-rates = [ 48000 ]
        audio.channels = 1
        audio.position = [ MONO ]
      }
    }
  }
]
